name: Publish Docker Image

# Ce workflow se déclenche uniquement quand on crée une Release sur GitHub
on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      # 1. Récupérer le code
      - name: Check out the repo
        uses: actions/checkout@v4

      # 2. Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Configurer Docker Buildx (outil de build avancé)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Build et Push
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # J'ai mis ton pseudo 'onelmelvy' ici directement :
          tags: onelmelvy/tp-cicd-github-actions:latest, onelmelvy/tp-cicd-github-actions:${{ github.event.release.tag_name }}